apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: yellowbooks-eks
  region: ap-southeast-1
  version: "${K8S_VERSION}"

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-default
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 30
    privateNetworking: false
